sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t bolormaa/react-test  -f ./client/Dockerfile.dev ./client

script:
  - docker  run -e CI=true bolormaa/react-test npm test 
after_success:
  - docker build -t bolormaa/multi-client ./client
  - docker build -t bolormaa/multi-nginx ./nginx
  - docker build -t bolormaa/multi-server ./server
  - docker build -t bolormaa/multi-worker ./worker